apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml
  - kube-prometheus-stack.yaml
  - metrics-server.yaml
configurations:
  - kustomizeconfig.yaml
